# Generated by Django 2.1.3 on 2018-11-16 00:28

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20181116_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=chat.models.gen_room_key, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subforum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.Subforum'),
            preserve_default=False,
        ),
    ]
